### PR TITLE
Fix nitro import

### PR DESCRIPTION
**Pull request by iaudouard**
## Pull request

Please ensure this PR targets the **`dev` branch** and follows the project conventions.  
CI already runs linting, formatting, and build checks automatically.

---

### Before submitting

- [x] This PR targets the `dev` branch (not `main`)
- [x] Commit messages follow the semantic-release format
- [x] No debug logs or sensitive data included

---

### Summary

Adds `NitroModules` import to `ios/GoogleMapViewImpl.swift` and `ios/RNGoogleMapsPlusModule.swift`.

---

### Type of change

- [ ] Feature
- [x] Fix
- [ ] Refactor
- [ ] Internal / CI
- [ ] Documentation

---

### Scope

- [ ] Android
- [x] iOS
- [ ] Core
- [ ] Example App
- [ ] Docs

---

### Related

---

### Additional notes

iOS build with Expo v54.0.22 was failing before the change.

```
❌  (node_modules/react-native-google-maps-plus/ios/GoogleMapViewImpl.swift:408:8)

  407 |     resultIsFile: Bool
> 408 |   ) -> NitroModules.Promise<String?> {
      |        ^ cannot find type 'NitroModules' in scope
  409 |     let promise = Promise<String?>()
  410 |
  411 |     onMainAsync {


❌  (node_modules/react-native-google-maps-plus/ios/GoogleMapViewImpl.swift:409:19)

  407 |     resultIsFile: Bool
  408 |   ) -> NitroModules.Promise<String?> {
  408 |   ) -> NitroModules.Promise<String?> {
> 409 |     let promise = Promise<String?>()
      |                   ^ cannot find 'Promise' in scope
  410 |
  411 |     onMainAsync {
  412 |       guard let mapView = self.mapView else {


❌  (node_modules/react-native-google-maps-plus/ios/GoogleMapViewImpl.swift:413:37)

  411 |     onMainAsync {
  412 |       guard let mapView = self.mapView else {
> 413 |         promise.resolve(withResult: nil)
      |                                     ^ 'nil' requires a contextual type
  414 |         return
  415 |       }
  416 |
  ```

### CODE REVIEW

**Comment by pinpong** [comment]
Thanks for the PR.
Which nitro-modules version are you working with because the ci pipeline compiles both platforms.

**Comment by iaudouard** [comment]
Hi, thanks for the prompt reply. I am using `v0.31.4`.
